[env]
ENV = "development"
BIN_NAME = "timer"
CONFIG_PATH = "./test/data/config.toml"

[settings]
experimental = true

[tools]
"go:github.com/spf13/cobra-cli" = "latest"

[tasks]
[tasks.build]
description = "build executable"
run = 'go build -o ./bin/{{env.BIN_NAME}} .'

[tasks.run]
description = "run the executable"
depends = ["build"]
run = "./bin/$BIN_NAME -c {{env.CONFIG_PATH}}"
